Add affiliation
kaka-ruto/carpitan pull request #27
Opened 2024-06-29 01:25 UTC by vyncem

https://github.com/kaka-ruto/carpitan/assets/3641733/69526ce4-ed67-409e-8973-3f790fc4a2c8

2024-07-01 14:49 UTC, kaka-ruto commented
Thanks for this @vyncem ! I will review soon. Meanwhile, check the failing tests.

2024-07-17 16:56 UTC, hmasila requested changes
Looks good. I have left a few comments for you to review/update

2024-07-17 16:56 UTC, hmasila commented on app/controllers/affiliations_controller.rb
> +    @affiliation = Affiliation.new(politician_id: affiliation_params[:politician_id], relationship: affiliation_params[:relationship], business_id: affiliation_params[:business_attributes][:id]) if a
You can wrap this in an if-else for easier readability

Also, not sure why we have the two ifs considering an affiliation belongs to a business, therefore, the business_id will always have to exist

2024-07-17 16:56 UTC, hmasila commented on app/controllers/affiliations_controller.rb
> +        format.html { redirect_to business_url(@affiliation), notice: "Business was successfully created." }
Is the flash message "Business was successfully created." or "Affiliation was successfully created."

2024-07-17 16:56 UTC, hmasila commented on app/controllers/affiliations_controller.rb
> +# Parameters: {"authenticity_token"=>"[FILTERED]", "affiliation"=>{"politician_id"=>"1", "relationship"=>"owned", "business"=>{"id"=>"1", "name"=>"", "business_phone"=>"", "business_email"=>"", "addr
You can remove the unused commented out code

2024-08-27 05:30 UTC, closed without merging